name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Checkout step
      uses: actions/checkout@v3

    - name: Create podman network
      run: make network

    - name: Create podman Postgresql DB
      run: make postgres

    - name: Make migrations
      run: make migrate_up

    - name: Test application
      run: make test
